### ISSUE TITLE
License for the Arduino Code?

### ISSUE THREAD

**Issue by dantheand** [klinquist/Arduino-Elevation-Display#1]
Hi @klinquist,

Thanks for this awesome repo! I found it via Google while looking for information to make my own car-based altimeter. It was an awesome resource and inspiration. This is my first hardware project!

I [forked your code](https://github.com/dantheand/arduino-elevation-display) because I had to make a few modifications given slight differences in hardware. 

Given that my code is an adaptation of yours I was wondering if you'd be able to say what license you'd like to apply to your original code. I'd love to be able to share mine via an MIT license if possible.

Thanks!
Dan

**Comment by klinquist** [comment]
Thanks for bringing this to my attention, I have added MIT license.
